name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Déclenche le workflow lorsqu'un push est effectué sur la branche principale (à adapter selon votre configuration)

jobs:
  build:
    runs-on: ubuntu-latest  # Spécifie l'image de l'agent à utiliser pour exécuter le travail

    steps:
      - name: Checkout Repository  # Étape pour récupérer le code source du référentiel
        uses: actions/checkout@v2

      - name: Set up JDK  # Étape pour configurer la version de Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Utilisation de Java 11

      - name: Build with Maven  # Étape pour construire le projet avec Maven
        run: mvn clean install  # Commande pour construire le projet avec Maven

      - name: Deploy to Azure Web App  # Étape pour déployer sur Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'VideoGamesDB'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: '*.war'
